### PR TITLE
Fixed usage in coroutines and updated with gmod-module-base headers

### PR DESCRIPTION
**Pull request by danielga**

### CODE REVIEW

**Comment by ARitz-Cracker** [comment]
Thank you so much

**Comment by ARitz-Cracker** [comment]
confirm working with following test code
```
require( "mysqloo" )
local t = coroutine.create( function()
	local db = mysqloo.connect( "192.168.0.4", "tester" , "tester123" , "test_db", 3306)
	print(db)
	function db:onConnected()
		print("Connected!")
		local t2 = coroutine.create( function()
			local q = db:query( "SELECT 1+1;" )
			function q:onSuccess( data )
				print(self:affectedRows().." rows")
				PrintTable(data)
			end
			function q:onError( err, sqlq )
				print("failed to query '"..sqlq.."' "..err)
			end
			q:start()
			print("Escape test: "..tostring(db:escape( "\"'faggot%" )))
			print("Status: "..tostring(db:status()))
			
			print("Ping: "..tostring(db:ping()))
			local pq = db:prepare("SELECT ?+?;")
			pq:setNumber(1, 2)
			pq:setNumber(2, 2)
			function pq:onSuccess( data )
				print(self:affectedRows().." rows")
				PrintTable(data)
			end
			function pq:onError( err, sqlq )
				print("failed to query '"..sqlq.."' "..err)
			end
			pq:start()
			print(tostring(pq:isRunning()))
			
			
			local t = db:createTransaction()
			t:addQuery(db:query( "SELECT 1+1;" ))
			t:addQuery(db:query( "SELECT 1+1;" ))
			function t:onSuccess()
				print("Transaction'd successfully")
			end
			function t:onError( err )
				print("failed to transactions "..err)
			end
			t:start()
			print("end of stuff")
			
			--db:disconnect(true)
		end)
		
		print(coroutine.resume( t2 ))
	end
	function db:onConnectionFailed(err)
		print("failed to connect "..err)
	end
	print(db.connect)
	db:connect()
end)
    
print(coroutine.resume( t ))
```

**Comment by SwadicalRag** [comment]
Fredy plz merge :+1:

**Comment by ARitz-Cracker** [comment]
🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉

**Pull request merged**
